export const LIST = "LIST_BANK_ACCOUNT";
export const LIST_SUCCESS = "LIST_BANK_ACCOUNT_SUCCESS";
export const LIST_FAILED = "LIST_BANK_ACCOUNT_FAILED";

export const ADD = "ADD_BANK_ACCOUNT";
export const ADD_SUCCESS = "ADD_BANK_ACCOUNT_SUCCESS";
export const ADD_FAILED = "ADD_BANK_ACCOUNT_FAILED";

export const EDIT = "EDIT_BANK_ACCOUNT";
export const EDIT_SUCCESS = "EDIT_BANK_ACCOUNT_SUCCESS";
export const EDIT_FAILED = "EDIT_BANK_ACCOUNT_FAILED";

export const DELETE = "DELETE_BANK_ACCOUNT";
export const DELETE_SUCCESS = "DELETE_BANK_ACCOUNT_SUCCESS";
export const DELETE_FAILED = "DELETE_BANK_ACCOUNT_FAILED";

export const RESET_DATA = "RESET_DATA_BANK_ACCOUNT";
