export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const MINUS_COUNT_CHECK = "MINUS_COUNT_CHECK";

export const GET_INFO = "GET_INFO_USER";
export const GET_INFO_SUCCESS = "GET_INFO_USER_SUCCESS";
export const GET_INFO_FAILED = "GET_INFO_USER_FAILED";
