export const ROUTES = {
  HOME_PAGE: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  SEARCH_TRANSACTION: "/search_transaction",
  CONTACT: "/contact",
  MENU: "/menu",
  NEWS: "/menu/news",
  QUESTION_ANSWER: "/menu/question_answer",
  GUIRE: "/menu/guire",
  PROFILE: "/profile",
  INFO: "/profile/info",
  BANK_ACCOUNT: "/profile/bank_account",
  WALLET: "/profile/wallet",
  HISTORIES: "/profile/histories",
  CHANGE_PASSWORD: "/profile/change_password",
};
