export const ROUTES = {
  HOME_PAGE: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  SEARCH_TRANSACTION: "/search_transaction",
  NEWS: "/news",
  CONTACT: "/contact",
  GUIRE: "/guire",
  PROFILE: "/profile",
  INFO: "/profile/info",
  BANK_ACCOUNT: "/profile/bank_account",
  WALLET: "/profile/wallet",
  HISTORIES: "/profile/histories",
  CHANGE_PASSWORD: "/profile/change_password",
};
