export const ADD = "ADD_CUSTOMER";
export const ADD_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_FAILED = "ADD_CUSTOMER_FAILED";

export const EDIT = "EDIT_CUSTOMER";
export const EDIT_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_FAILED = "EDIT_CUSTOMER_FAILED";

export const RESET_DATA = "RESET_DATA_CUSTOMER";
