export const LIST = "LIST_GUIRE";
export const LIST_SUCCESS = "LIST_GUIRE_SUCCESS";
export const LIST_FAILED = "LIST_GUIRE_FAILED";

export const DETAIL = "DETAIL_GUIRE";
export const DETAIL_SUCCESS = "DETAIL_GUIRE_SUCCESS";
export const DETAIL_FAILED = "DETAIL_GUIRE_FAILED";

export const RESET_DATA = "RESET_DATA_GUIRE";
